"[BUG]": "T.0 - Bug"
"[FIX]": "T.0 - Bug"
"[ENH]": "T.1 - Enhancement"
"[MAINT]": "T.2 - Maintenance"
"[MNT]": "T.2 - Maintenance"
"[STY]": "T.2 - Maintenance"
"[TYP]": "T.2 - Maintenance"
"[DOC]": "T.3 - Documentation"
"[TST]": "T.4 - Testing"
"[DEP]": "T.5 - Deprecation"
"[REL]": "T.6 - Release"
