changelog:
  exclude:
    authors:
      - pre-commit-ci
      - dependabot[bot]
  categories:
    - title: Breaking Changes
      labels:
        - P.0 - Breaking change
    - title: Features
      labels:
        - T.1 - Enhancement
    - title: Bug Fixes
      labels:
        - T.0 - Bug
    - title: Deprecations
      labels:
        - T.5 - Deprecation
    - title: Documentation
      labels:
        - T.3 - Documentation
    - title: Maintenance
      labels:
        - T.2 - Maintenance
        - T.4 - Testing
    - title: Misc
      labels:
        - "*"
