[build-system]
build-backend = "hatchling.build"
requires = ["hatch-vcs", "hatchling"]

[project]
authors = [{ name = "Nipoppy developpers" }]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
]
dependencies = [
    "boutiques>=0.5.31",
    "click",
    "httpx",
    "jinja2",
    "json5",
    "pandas",
    "pybids!=0.18.0",
    "pydantic",
    "pydicom!=3.0.0",
    "pysqa[sge]>=0.2.4",
    "python-dotenv",
    "rich",
    "rich-click",
    "typing-extensions",
]
description = "Standardized organization and processing of neuroimaging-clinical datasets"
license = { file = "LICENSE" }
name = "nipoppy"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]

[project.optional-dependencies]
parallel = ["joblib"]
doc = [
    "furo==2025.12.19",
    "mdit-py-plugins==0.6.1",
    "myst-parser==4.0.1 ; python_version < '3.11'",
    "myst-parser==5.1.0 ; python_version >= '3.11'",
    "sphinx==8.1.3",
    "sphinx-autoapi==3.8.0",
    "sphinx-click==6.2.0",
    "sphinx-copybutton==0.5.2",
    "sphinx-github-changelog==1.7.2",
    "sphinx-jsonschema==1.19.2",
    "sphinx-togglebutton==0.4.5",
    "sphinx_design==0.6.1",
    "Sphinx-Substitution-Extensions==2026.01.12",
]
dev = ["nipoppy[doc,test]", "pre-commit"]
test = [
    "bids-validator-deno",
    "fids>=0.1.0",
    "nipoppy[gui,parallel]",
    "packaging",
    "pytest-cov",
    "pytest-httpx",
    "pytest-mock",
    "pytest-xdist",
    "pytest>=6.0.0",
]
tests = ["nipoppy[test]"] # alias in case of typo
tui = ["trogon"]
gui = ["nipoppy[tui]"] # alias for TUI

[project.scripts]
nipoppy = "nipoppy.cli.cli:cli"
nipoppy-gui = "nipoppy.cli.cli:tui_launch"

[tool.hatch.build.targets.wheel]
packages = ["nipoppy"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.hooks.vcs]
version-file = "nipoppy/_version.py"

[tool.hatch.version]
source = "vcs"

[tool.codespell]
skip = '.git,.github,pyproject.toml'

[tool.pytest.ini_options]
addopts = "--color=yes -n auto --dist loadfile -ra -q -vv"
testpaths = ["tests/"]
minversion = "6.0"
xfail_strict = true
markers = [
    "api: mark a test as an api test.",
    "linkcheck: mark a test as a link check test.",
    "no_xdist: mark a test that should not be run with xdist in CI.",
]

[tool.coverage.report]
# Preserves the "pragma: no cover" and skip functions decorated with "@abstractmethod"
# More info at: https://coverage.readthedocs.io/en/latest/config.html#report-exclude-also
exclude_also = ["@abstractmethod"]
