name: Bug report

# See the json schema to help you create / update this form
# https://json.schemastore.org/github-issue-forms.json

description: Fill in this template to report a bug

title: "[BUG] "

labels: ["type:bug"]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description:
        Please search to see if an issue already exists for the bug you
        encountered.
      options:
        - label: I have searched the existing issues

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what outcome you expected.
      placeholder: Describe what outcome you expected.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Current Behavior
      description: Describe what you got instead.
      placeholder: Describe what you got instead.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error message
      description: If possible paste below the error message you encountered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Environment
      description: |
        If necessary give information about your setup.
      value: |
        - OS:
        - Python/Node version:
    validations:
      required: false

  # - type: textarea
  #   attributes:
  #     label: Version
  #     description: |
  #       Which version did you encounter this bug on?
  #     value: |
  #       - version:

  - type: textarea
    attributes:
      label: How to reproduce
      description: |
        What is the command you ran? 

        Ideally provide a minimal example that reproduces the bug.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
