name: Label new issues

on:
  issues:
    types:
      - opened

jobs:
  label:
    name: Label issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: github.repository == 'nipoppy/nipoppy'
    steps:
      - name: Label the issue
        uses: gerrymanoim/pr-prefix-labeler@c8062327f6de59a9ae1c19f7f07cacd0b976b6fa # v3
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
