# Ref URL: https://github.com/actions/stale
name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "0 11 * * *" # Every day at 11:00 UTC

permissions:
  actions: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open 5 months with no activity."
          stale-pr-message: "This PR is stale because it has been open 45 days with no activity."
          days-before-issue-stale: 150 # ~5 months
          days-before-issue-close: -1 # never
          days-before-pr-stale: 45
          days-before-pr-close: -1 # never
